--Discovery Flights usage by FSP Operator

SELECT DF.OPERATORID,
DF.ISENABLED,
DF.ENABLEDATUTC,
DFP.FIRSTDISCODATE,
LMREV.AMOUNT as DISCO_REV_LAST_MONTH,
MTDREV.AMOUNT as DISCO_REV_MTD,
LWREV.AMOUNT as DISCO_REV_LAST_WEEK

FROM FSP_SOURCES.FSP_V3_PRODUCTION_DFL.DFL_DISCOVERYFLIGHTSETTINGS DF

LEFT JOIN(
SELECT OPERATORID, MIN(CREATEDATUTC) AS FIRSTDISCODATE
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DFL.DFL_DISCOVERYFLIGHTPURCHASES 
WHERE STATUS = 'Purchased'
GROUP BY OPERATORID
) DFP
ON DFP.OPERATORID = DF.OPERATORID

LEFT JOIN(
SELECT OPERATORID, SUM(AMOUNT) AS AMOUNT
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DFL.DFL_DISCOVERYFLIGHTPURCHASES
WHERE STATUS = 'Purchased'
AND CREATEDATUTC >= DATE_TRUNC('month', DATEADD(month, -1, CURRENT_DATE()))
AND CREATEDATUTC < DATE_TRUNC('month', CURRENT_DATE())
GROUP BY OPERATORID
) LMREV
ON LMREV.OPERATORID = DF.OPERATORID

LEFT JOIN(
SELECT OPERATORID, SUM(AMOUNT) AS AMOUNT
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DFL.DFL_DISCOVERYFLIGHTPURCHASES
WHERE STATUS = 'Purchased'
AND CREATEDATUTC >= DATE_TRUNC('month', CURRENT_DATE())
GROUP BY OPERATORID
) MTDREV
ON MTDREV.OPERATORID = DF.OPERATORID

LEFT JOIN(
SELECT OPERATORID, SUM(AMOUNT) AS AMOUNT
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DFL.DFL_DISCOVERYFLIGHTPURCHASES
WHERE STATUS = 'Purchased'
AND CREATEDATUTC >= DATEADD(week, -1, DATE_TRUNC('week', CURRENT_DATE()))
AND CREATEDATUTC < DATE_TRUNC('week', CURRENT_DATE())
GROUP BY OPERATORID
) LWREV
ON LWREV.OPERATORID = DF.OPERATORID

GROUP BY 
DF.OPERATORID,
DF.ISENABLED,
DF.ENABLEDATUTC,
DFP.FIRSTDISCODATE,
LMREV.AMOUNT,
MTDREV.AMOUNT,
LWREV.AMOUNT