SELECT SO.ID AS MAXIOID,
SO.NUMBER AS MAXIONUMBER,
SO.CUSTOM_CHARGIFY_ID,
SO.IS_ACTIVE as MAXIOACTIVE,
FSP.ID AS FSPID,
FSP.ISACTIVE AS FSPACTIVE,
FSP.ISINTERNAL AS FSPINTERNAL,
MA.EXTERNALID AS PAYRIXMID,
CASE WHEN MA.STATUSID = 2 THEN TRUE WHEN MA.EXTERNALID IS NOT NULL THEN FALSE ELSE NULL END AS PAYRIXACTIVE, 
HS.ID AS HUBSPOTID,
SO.NAME AS MAXIONAME,
FSP.CUSTOMERCOMPANYNAME AS FSPNAME

FROM PC_FIVETRAN_DB.MAXIO_SAASOPTICS.CUSTOMER SO
LEFT JOIN FSP_SOURCES.FSP_V3_PRODUCTION_DBO.CHARGIFYSUBSCRIPTIONS CS ON CS.CHARGIFYCUSTOMERID = SO.CUSTOM_CHARGIFY_ID
FULL JOIN FSP_SOURCES.FSP_V3_PRODUCTION_DBO.TBLCOMPANY FSP ON FSP.ID = CS.OPERATORID
LEFT JOIN FSP_SOURCES.FSP_V3_PRODUCTION_INV.INV_MERCHANTACCOUNTS MA ON MA.OPERATORID = CS.OPERATORID
LEFT JOIN PC_FIVETRAN_DB.HUBSPOT.COMPANY HS ON HS.PROPERTY_FSP_ID = FSP.ID

GROUP BY SO.ID,
SO.NUMBER,
SO.CUSTOM_CHARGIFY_ID,
SO.IS_ACTIVE,
FSP.ID,
FSP.ISACTIVE,
FSP.ISINTERNAL,
MA.EXTERNALID,
MA.STATUSID,
HS.ID,
SO.NAME,
FSP.CUSTOMERCOMPANYNAME