--Ground school usage and transaction dates by FSP Operator ID

SELECT CO.OPERATORID, 
CO.CUSTOMERCOMPANYNAME,
SPTEN.SPORTYSENABLED,
AVPROEN.AVPROENABLED,
SPTEO.SPORTYSENABLEDON,
AVPROEO.AVPROENABLEDON,
SPTFIRST.SPORTYSFIRSTSALEDATE,
AVPROFIRST.AVPROFIRSTSALEDATE,
SPTLAST.SPORTYSLASTSALEDATE,
AVPROLAST.AVPROLASTSALEDATE,
SXC.SXTYCOURSESSOLD, 
TWTC.TWTCCOURSESSOLD,
TOT.TOTALCOURSESSOLD,
LMGS.AMOUNT AS GROUND_SCHOOL_SALES_LAST_MONTH,
MTDGS.AMOUNT AS GROUND_SCHOOL_SALES_MTD,
LWGS.AMOUNT AS GROUND_SCHOOL_SALES_LAST_WEEK

FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.TBLCOMPANY CO

LEFT JOIN
(SELECT OPERATORID,
ISENABLED AS SPORTYSENABLED
FROM FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTS
WHERE ISENABLED = 'TRUE'
AND CONTENTPROVIDERTYPE = 1) SPTEN ON SPTEN.OPERATORID = CO.OPERATORID

LEFT JOIN
(SELECT OPERATORID,
ISENABLED AS AVPROENABLED
FROM FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTS
WHERE ISENABLED = 'TRUE'
AND CONTENTPROVIDERTYPE = 2) AVPROEN ON AVPROEN.OPERATORID = CO.OPERATORID

LEFT JOIN 
(SELECT OPERATORID, 
MIN(PERFORMEDATUTC) AS SPORTYSENABLEDON
FROM FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTHISTORY
WHERE ACTION = 'Enabled'
AND CONTENTPROVIDERTYPE = 1
GROUP BY OPERATORID
) SPTEO ON SPTEO.OPERATORID = CO.OPERATORID

LEFT JOIN 
(SELECT OPERATORID, 
MIN(PERFORMEDATUTC) AS AVPROENABLEDON
FROM FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTHISTORY
WHERE ACTION = 'Enabled'
AND CONTENTPROVIDERTYPE = 2
GROUP BY OPERATORID
) AVPROEO ON AVPROEO.OPERATORID = CO.OPERATORID

LEFT JOIN (
SELECT OPERATORID, 
MIN(SALESTRANSACTIONDATE) AS SPORTYSFIRSTSALEDATE
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND NAME LIKE '%Sport%'
GROUP BY OPERATORID
) SPTFIRST ON SPTFIRST.OPERATORID = CO.OPERATORID

LEFT JOIN (
SELECT OPERATORID, 
MIN(SALESTRANSACTIONDATE) AS AVPROFIRSTSALEDATE
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND NAME LIKE '%Aviator%'
GROUP BY OPERATORID
) AVPROFIRST ON AVPROFIRST.OPERATORID = CO.OPERATORID

LEFT JOIN (
SELECT OPERATORID, 
MAX(SALESTRANSACTIONDATE) AS SPORTYSLASTSALEDATE
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND NAME LIKE '%Sport%'
GROUP BY OPERATORID
) SPTLAST ON SPTLAST.OPERATORID = CO.OPERATORID

LEFT JOIN (
SELECT OPERATORID, 
MAX(SALESTRANSACTIONDATE) AS AVPROLASTSALEDATE
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND NAME LIKE '%Aviator%'
GROUP BY OPERATORID
) AVPROLAST ON AVPROLAST.OPERATORID = CO.OPERATORID


LEFT JOIN 
(SELECT LIS.OPERATORID, SUM(LIS.QUANTITY) as SXTYCOURSESSOLD
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS LIS
JOIN
(select OPERATORID, MIN(PERFORMEDATUTC) as ENABLEDON
from FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTHISTORY
where ACTION = 'Enabled'
group by OPERATORID) EOS on EOS.OPERATORID = LIS.OPERATORID
where LIS.SALESTRANSACTIONDATE between EOS.ENABLEDON and DATEADD(day, 60, EOS.ENABLEDON)
and LIS.ITEMTYPEID = 111
group by LIS.OPERATORID
) SXC on SXC.OPERATORID = CO.OPERATORID

LEFT JOIN 
(select LIT.OPERATORID, SUM(LIT.QUANTITY) as TWTCCOURSESSOLD
from FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS LIT
join
(select OPERATORID, MIN(PERFORMEDATUTC) as ENABLEDON
from FSP_SOURCES.CURRICULUMTRACKING_PROD_DBO.CONTENTPROVIDERACCOUNTHISTORY
where ACTION = 'Enabled'
group by OPERATORID) EOT on EOT.OPERATORID = LIT.OPERATORID
where LIT.SALESTRANSACTIONDATE between EOT.ENABLEDON and DATEADD(day, 120, EOT.ENABLEDON)
and LIT.ITEMTYPEID = 111
group by LIT.OPERATORID
) TWTC on TWTC.OPERATORID = CO.OPERATORID

LEFT JOIN
(SELECT OPERATORID, SUM(QUANTITY) as TOTALCOURSESSOLD
from FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
GROUP BY OPERATORID
) TOT ON TOT.OPERATORID = CO.OPERATORID

LEFT JOIN
(SELECT OPERATORID, SUM(NETAMOUNT) AS AMOUNT,
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND SALESTRANSACTIONDATE >= DATE_TRUNC('month', DATEADD(month, -1, CURRENT_DATE()))
AND SALESTRANSACTIONDATE < DATE_TRUNC('month', CURRENT_DATE())
GROUP BY OPERATORID
) LMGS ON LMGS.OPERATORID = CO.OPERATORID

LEFT JOIN
(SELECT OPERATORID, SUM(NETAMOUNT) AS AMOUNT,
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND SALESTRANSACTIONDATE >= DATE_TRUNC('month', CURRENT_DATE())
GROUP BY OPERATORID
) MTDGS ON MTDGS.OPERATORID = CO.OPERATORID

LEFT JOIN
(SELECT OPERATORID, SUM(NETAMOUNT) AS AMOUNT,
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS
WHERE ITEMTYPEID = 111
AND SALESTRANSACTIONDATE >= DATEADD(week, -1, DATE_TRUNC('week', CURRENT_DATE()))
AND SALESTRANSACTIONDATE < DATE_TRUNC('week', CURRENT_DATE())
GROUP BY OPERATORID
) LWGS ON LWGS.OPERATORID = CO.OPERATORID


WHERE SPORTYSENABLEDON IS NOT NULL OR AVPROENABLEDON IS NOT NULL

GROUP BY
CO.OPERATORID, 
CO.CUSTOMERCOMPANYNAME,
SPTEN.SPORTYSENABLED,
AVPROEN.AVPROENABLED,
SPTEO.SPORTYSENABLEDON,
AVPROEO.AVPROENABLEDON,
SPTFIRST.SPORTYSFIRSTSALEDATE,
AVPROFIRST.AVPROFIRSTSALEDATE,
SPTLAST.SPORTYSLASTSALEDATE,
AVPROLAST.AVPROLASTSALEDATE,
SXC.SXTYCOURSESSOLD, 
TWTC.TWTCCOURSESSOLD,
TOT.TOTALCOURSESSOLD,
LMGS.AMOUNT,
MTDGS.AMOUNT,
LWGS.AMOUNT