--Payment transactions by FSP Operator ID

WITH boarded AS (
    SELECT OPERATORID, MIN(EXTERNALBOARDEDDATE) AS BOARDEDDATE
    FROM FSP_SOURCES.FSP_V3_PRODUCTION_INV.INV_MERCHANTACCOUNTS
    GROUP BY OPERATORID
),
txn AS (
    SELECT
        TXP.OPERATORID,
        TXP.SALESTRANSACTIONID,
        TXP.PAYMENTDATE,
        TXP.SALESTRANSACTIONDATE,
        TXP.AMOUNT,
        BD.BOARDEDDATE
    FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONPAYMENTS TXP
    LEFT JOIN boarded BD ON BD.OPERATORID = TXP.OPERATORID
    WHERE TXP.EXTERNALTRANSACTIONID IS NOT NULL
),
agg AS (
    SELECT
        OPERATORID,
        SUM(CASE WHEN SALESTRANSACTIONDATE BETWEEN BOARDEDDATE AND DATEADD(day, 60,  BOARDEDDATE)
                 THEN AMOUNT END) AS SxtyTXNAmount,
        SUM(CASE WHEN SALESTRANSACTIONDATE BETWEEN BOARDEDDATE AND DATEADD(day, 120, BOARDEDDATE)
                 THEN AMOUNT END) AS OneTwtyTXNAmount,
        SUM(CASE WHEN SALESTRANSACTIONDATE >= DATE_TRUNC('month', DATEADD('month', -1, CURRENT_DATE))
                  AND SALESTRANSACTIONDATE <  DATE_TRUNC('month', CURRENT_DATE)
                 THEN AMOUNT END) AS LastMnthAmount,
        MIN(PAYMENTDATE) AS First_Txn
    FROM txn
    GROUP BY OPERATORID
),
tenk AS (
    SELECT OPERATORID, PAYMENTDATE AS threshold_date
    FROM (
        SELECT
            OPERATORID,
            PAYMENTDATE,
            SALESTRANSACTIONID,
            SUM(AMOUNT) OVER (PARTITION BY OPERATORID
                              ORDER BY PAYMENTDATE, SALESTRANSACTIONID) AS running_total
        FROM txn
    )
    WHERE running_total >= 10000
    QUALIFY ROW_NUMBER() OVER (PARTITION BY OPERATORID
                               ORDER BY PAYMENTDATE, SALESTRANSACTIONID) = 1
)
SELECT
    CO.OPERATORID,
    CO.CUSTOMERCOMPANYNAME,
    BD.BOARDEDDATE,
    agg.SxtyTXNAmount,
    agg.OneTwtyTXNAmount,
    agg.LastMnthAmount,
    agg.First_Txn,
    tenk.threshold_date
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.TBLCOMPANY CO
JOIN      boarded BD  ON BD.OPERATORID   = CO.OPERATORID
LEFT JOIN agg         ON agg.OPERATORID  = CO.OPERATORID
LEFT JOIN tenk        ON tenk.OPERATORID = CO.OPERATORID
WHERE CO.ISACTIVE = 1
  AND CO.ISINTERNAL = 0;