SELECT YEAR(ST.DATE) as YEAR, 
MONTH(ST.DATE) AS MONTH, 
COUNT(DISTINCT ST.OPERATORID) AS FSP_Companies,
SUM(LI.NETAMOUNT) AS AMOUNT,
SUM(LI.NETAMOUNT)/COUNT(DISTINCT ST.OPERATORID) as AVG_PER_COMPANY
FROM FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONLINEITEMS LI
JOIN FSP_SOURCES.FSP_V3_PRODUCTION_DBO.SALESTRANSACTIONS ST 
    ON ST.SALESTRANSACTIONID = LI.SALESTRANSACTIONID
    AND ST.PURCHASESOURCE = 3
WHERE LI.ITEMTYPEID != 111
GROUP BY YEAR(ST.DATE), MONTH(ST.DATE)
ORDER BY YEAR(ST.DATE), MONTH(ST.DATE)